### ISSUE TITLE
Crash with both latest versions

### ISSUE THREAD

**Issue by PSYCHO1512** [ClousClouds/ClearLagg#6]
PocketMine-MP Crash Dump Tue Dec 3 17:53:06 UTC 2024

PocketMine-MP version: 5.21.1 [Protocol 748]
Git commit: 4a702b97fd282731622f40692921e6f5763a9571
PHP version: 8.2.25
OS: Linux, linux

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: ClearLagg

Thread: Main
Error: pocketmine\Server::broadcastMessage(): Argument #1 ($message) must be of type pocketmine\lang\Translatable|string, null given, called in phar:///home/container/plugins/ClearLagg.phar/src/KnosTx/ClearLagg/manager/ClearLaggManager.php on line 81
File: pmsrc/src/Server
Line: 1291
Type: TypeError
Backtrace:
#0 plugins/ClearLagg.phar/src/KnosTx/ClearLagg/manager/ClearLaggManager(81): pocketmine\Server->broadcastMessage(null)
#1 plugins/ClearLagg.phar/src/KnosTx/ClearLagg/Main(82): KnosTx\ClearLagg\manager\ClearLaggManager->clearItems()
#2 pmsrc/src/command/PluginCommand(46): KnosTx\ClearLagg\Main->onCommand(object pocketmine\player\Player#151152, object pocketmine\command\PluginCommand#49501, string[9] clearlagg, array[0])
#3 pmsrc/src/command/SimpleCommandMap(212): pocketmine\command\PluginCommand->execute(object pocketmine\player\Player#151152, string[9] clearlagg, array[0])
#4 pmsrc/src/Server(1431): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#151152, string[10] clearlagg )
#5 pmsrc/src/player/Player(1521): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#151152, string[10] clearlagg )
#6 pmsrc/src/network/mcpe/handler/InGamePacketHandler(819): pocketmine\player\Player->chat(string[11] /clearlagg )
#7 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#103671)
#8 pmsrc/src/network/mcpe/NetworkSession(472): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#131210)
#9 pmsrc/src/network/mcpe/NetworkSession(410): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#103671, string[33] M./clearlagg ..BK..J.|-}...i....T)
#10 pmsrc/src/network/mcpe/raklib/RakLibInterface(214): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[35] .!M./clearlagg ..BK..J.|-}...i....T)
#11 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[44] ...]..'..-.......p..W.N...'.D..{...../....>.)
#12 pmsrc/src/network/mcpe/raklib/RakLibInterface(107): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#184560)
#13 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\TimeTrackingSleeperHandler->pocketmine\{closure}()
#15 pmsrc/src/TimeTrackingSleeperHandler(77): pocketmine\snooze\SleeperHandler->processNotifications()
#16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#17 pmsrc/src/Server(1698): pocketmine\snooze\SleeperHandler->sleepUntil(float 1733248386.3962)
#18 pmsrc/src/Server(1066): pocketmine\Server->tickProcessor()
#19 pmsrc/src/PocketMine(355): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#2, string[16] /home/container/, string[24] /home/container/plugins/)
#20 pmsrc/src/PocketMine(378): pocketmine\server()
#21 /home/container/PocketMine-MP.phar(168): require(string[72] phar:///tmp/PocketMine-MP-phar-cache.0/PMMPIfojCg.tar/src/PocketMine.php)

Code:
[1282] 	 * @phpstan-return array<int, CommandSender>
[1283] 	 */
[1284] 	public function getBroadcastChannelSubscribers(string $channelId) : array{
[1285] 		return $this->broadcastSubscribers[$channelId] ?? [];
[1286] 	}
[1287] 
[1288] 	/**
[1289] 	 * @param CommandSender[]|null $recipients
[1290] 	 */
[1291] 	public function broadcastMessage(Translatable|string $message, ?array $recipients = null) : int{
[1292] 		$recipients = $recipients ?? $this->getBroadcastChannelSubscribers(self::BROADCAST_CHANNEL_USERS);
[1293] 
[1294] 		foreach($recipients as $recipient){
[1295] 			$recipient->sendMessage($message);
[1296] 		}
[1297] 
[1298] 		return count($recipients);
[1299] 	}
[1300] 
[1301] 	/**

**Comment by KnosTx** [comment]
Thank you, I will report this error to the Team.

**Comment by PSYCHO1512** [comment]
is the error fixed

**Comment by KnosTx** [comment]
The problem has been resolved.
